version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    depends_on:
      - backend  
  frontend:
    image: arti1946/foodgram-frontend
    env_file: .env  
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: arti1946/foodgram-gateway
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - static:/staticfiles/
      - media:/app/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
  backend:
    image: arti1946/foodgram-backend
    env_file: .env
    volumes: 
      - static:/backend_static
      - media:/app/media/
