# Generated by Django 3.2.3 on 2023-08-24 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodgram", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipes",
            options={"ordering": ["-pub_date"]},
        ),
    ]
